// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LsOEKN12K7SsDTC1c_jGC_1nUD_M-hQ',
    appId: '1:370971888169:web:bbfcbba8491e9c5a3c6a38',
    messagingSenderId: '370971888169',
    projectId: 'authentication-3b7af',
    authDomain: 'authentication-3b7af.firebaseapp.com',
    databaseURL: 'https://authentication-3b7af-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-3b7af.firebasestorage.app',
    measurementId: 'G-H44SXKE0BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSljVvogqGBqIOPl71NwfPVchRNTihTnM',
    appId: '1:370971888169:android:300dcea989034a673c6a38',
    messagingSenderId: '370971888169',
    projectId: 'authentication-3b7af',
    databaseURL: 'https://authentication-3b7af-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-3b7af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK9x_mZkscHDYksUjK5n7oEbK1Pj2jxzs',
    appId: '1:370971888169:ios:317b920f78b9fef43c6a38',
    messagingSenderId: '370971888169',
    projectId: 'authentication-3b7af',
    databaseURL: 'https://authentication-3b7af-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-3b7af.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
